[package]
name         = "esp-build"
version      = "0.1.0"
edition      = "2021"
rust-version = "1.60.0"
description  = "Build utilities for esp-hal"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote     = "1.0.37"
syn       = { version = "2.0.71", features = ["fold", "full"] }
termcolor = "1.4.1"
