[package]
name    = "qa-test"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
blocking-network-stack = { git = "https://github.com/bjoernQ/blocking-network-stack.git", rev = "b3ecefc", optional = true }
cfg-if = "1.0.0"
embassy-executor = "0.9.0"
embassy-time = "0.5.0"
embassy-futures = "0.1"
embassy-net = { version = "0.7.0", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet"] }
embassy-sync = "0.6.1"
embedded-graphics = "0.8.1"
embedded-hal-async = "1.0.0"
embedded-io = { version = "0.6.1", default-features = false }
esp-alloc = { path = "../esp-alloc" }
esp-backtrace = { path = "../esp-backtrace", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { path = "../esp-bootloader-esp-idf" }
esp-hal = { path = "../esp-hal", features = ["log-04", "unstable"] }
esp-rtos = { path = "../esp-rtos", features = [
    "log-04",
    "embassy",
] }
esp-println = { path = "../esp-println", features = ["log-04"] }
esp-radio = { path = "../esp-radio", features = [
    "log-04",
    "smoltcp",
    "unstable",
    "wifi",
], optional = true }
lis3dh-async = "0.9.3"
ssd1306 = "0.10.0"
smoltcp = { version = "0.12.0", default-features = false, features = [
    "medium-ethernet",
    "socket-raw",
], optional = true }
static_cell = "2.1.1"

[features]
unstable = []

esp-radio = [
    "dep:blocking-network-stack",
    "dep:esp-radio",
    "dep:smoltcp",
]

esp32 = [
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-hal/esp32",
    "esp-rtos/esp32",
    "esp-println/esp32",
    "esp-radio?/esp32",
]
esp32c2 = [
    "esp-backtrace/esp32c2",
    "esp-bootloader-esp-idf/esp32c2",
    "esp-hal/esp32c2",
    "esp-rtos/esp32c2",
    "esp-println/esp32c2",
    "esp-radio?/esp32c2",
]
esp32c3 = [
    "esp-backtrace/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-println/esp32c3",
    "esp-radio?/esp32c3",
]
esp32c6 = [
    "esp-backtrace/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-hal/esp32c6",
    "esp-rtos/esp32c6",
    "esp-println/esp32c6",
    "esp-radio?/esp32c6",
]
esp32h2 = [
    "esp-backtrace/esp32h2",
    "esp-bootloader-esp-idf/esp32h2",
    "esp-hal/esp32h2",
    "esp-rtos/esp32h2",
    "esp-println/esp32h2",
    "esp-radio?/esp32h2",
]
esp32s2 = [
    "esp-backtrace/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
    "esp-hal/esp32s2",
    "esp-rtos/esp32s2",
    "esp-println/esp32s2",
    "esp-radio?/esp32s2",
]
esp32s3 = [
    "esp-backtrace/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-hal/esp32s3",
    "esp-rtos/esp32s3",
    "esp-println/esp32s3",
    "esp-radio?/esp32s3",
]

[profile.release]
debug            = 2
debug-assertions = true
lto              = "fat"
codegen-units    = 1
