[package]
name    = "qa-test"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
cfg-if             = "1.0.0"
embassy-executor   = { version = "0.7.0", features = ["task-arena-size-12288"] }
embassy-time       = "0.4.0"
embassy-futures    = "0.1.1"
embassy-sync    = "0.6.1"
embedded-graphics  = "0.8.1"
embedded-hal-async = "1.0.0"
esp-alloc          = { path = "../esp-alloc" }
esp-backtrace      = { path = "../esp-backtrace", features = ["exception-handler", "panic-handler", "println"] }
esp-hal            = { path = "../esp-hal", features = ["unstable"] }
esp-hal-embassy    = { path = "../esp-hal-embassy" }
esp-println        = { path = "../esp-println", features = ["log"] }
lis3dh-async       = "0.9.3"
ssd1306            = "0.9.0"

[features]
esp32   = ["esp-backtrace/esp32",   "esp-hal/esp32",   "esp-hal-embassy/esp32",   "esp-println/esp32"]
esp32c2 = ["esp-backtrace/esp32c2", "esp-hal/esp32c2", "esp-hal-embassy/esp32c2", "esp-println/esp32c2"]
esp32c3 = ["esp-backtrace/esp32c3", "esp-hal/esp32c3", "esp-hal-embassy/esp32c3", "esp-println/esp32c3"]
esp32c6 = ["esp-backtrace/esp32c6", "esp-hal/esp32c6", "esp-hal-embassy/esp32c6", "esp-println/esp32c6"]
esp32h2 = ["esp-backtrace/esp32h2", "esp-hal/esp32h2", "esp-hal-embassy/esp32h2", "esp-println/esp32h2"]
esp32s2 = ["esp-backtrace/esp32s2", "esp-hal/esp32s2", "esp-hal-embassy/esp32s2", "esp-println/esp32s2"]
esp32s3 = ["esp-backtrace/esp32s3", "esp-hal/esp32s3", "esp-hal-embassy/esp32s3", "esp-println/esp32s3"]

[profile.release]
debug         = 2
debug-assertions = true
lto           = "fat"
codegen-units = 1
