[package]
name    = "ota_update"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cfg-if = "1.0.0"
embedded-storage = "0.3.1"
esp-backtrace = { path = "../../../esp-backtrace", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { path = "../../../esp-bootloader-esp-idf" }
esp-hal = { path = "../../../esp-hal", features = ["log-04", "unstable"] }
esp-println = { path = "../../../esp-println", features = ["log-04"] }
esp-storage = { path = "../../../esp-storage" }

[features]
esp32 = [
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-hal/esp32",
    "esp-storage/esp32",
]
esp32c2 = [
    "esp-backtrace/esp32c2",
    "esp-bootloader-esp-idf/esp32c2",
    "esp-hal/esp32c2",
    "esp-storage/esp32c2",
]
esp32c3 = [
    "esp-backtrace/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
    "esp-hal/esp32c3",
    "esp-storage/esp32c3",
]
esp32c6 = [
    "esp-backtrace/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-hal/esp32c6",
    "esp-storage/esp32c6",
]
esp32h2 = [
    "esp-backtrace/esp32h2",
    "esp-bootloader-esp-idf/esp32h2",
    "esp-hal/esp32h2",
    "esp-storage/esp32h2",
]
esp32s2 = [
    "esp-backtrace/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
    "esp-hal/esp32s2",
    "esp-storage/esp32s2",
]
esp32s3 = [
    "esp-backtrace/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-hal/esp32s3",
    "esp-storage/esp32s3",
]

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1
