[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.79"
clap       = { version = "4.5.0",  features = ["derive"] }
env_logger = "0.11.1"
log        = "0.4.20"
strum      = { version = "0.26.1", features = ["derive"] }
