[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.86"
basic-toml = "0.1.9"
chrono     = "0.4.38"
clap       = { version = "4.5.4",  features = ["derive"] }
csv        = "1.3.0"
env_logger = "0.11.3"
log        = "0.4.21"
minijinja  = "2.0.1"
semver     = { version = "1.0.23",  features = ["serde"] }
serde      = { version = "1.0.203", features = ["derive"] }
strum      = { version = "0.26.2",  features = ["derive"] }
toml_edit  = "0.22.13"
esp-metadata = { path = "../esp-metadata", features = ["clap"] }
