[package]
name         = "esp32h2-hal"
version      = "0.6.1"
edition      = "2021"
rust-version = "1.67.0"
description  = "HAL for ESP32-H2 microcontrollers"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

keywords = [
    "embedded",
    "embedded-hal",
    "esp",
    "esp32h2",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[dependencies]
esp-hal-common = { version = "0.15.0", features = ["esp32h2"], path = "../esp-hal-common" }

[dev-dependencies]
aes                = "0.8.3"
critical-section   = "1.1.2"
crypto-bigint      = { version = "0.5.5", default-features = false }
elliptic-curve     = { version = "0.13.8", default-features = false, features = ["sec1"] }
embassy-executor   = { version = "0.5.0", features = ["nightly"] }
embassy-sync       = "0.5.0"
embassy-time       = "0.3.0"
embedded-graphics  = "0.8.1"
embedded-hal-1     = { version = "1.0.0", package = "embedded-hal" }
embedded-hal-async = "1.0.0"
embedded-can       = "0.4.1"
embedded-io-async  = "0.6.1"
embedded-hal-bus   = "0.1.0"
esp-backtrace      = { version = "0.10.0", features = ["esp32h2", "panic-handler", "exception-handler", "print-uart"] }
esp-hal-smartled   = { version = "0.8.0", features = ["esp32h2"], path = "../esp-hal-smartled" }
esp-println        = { version = "0.8.0", features = ["esp32h2"] }
heapless           = "0.8.0"
hex-literal        = "0.4.1"
hmac               = { version = "0.12.1", default-features = false }
lis3dh-async       = "0.9.1"
p192               = { version = "0.13.0", default-features = false, features = ["arithmetic"] }
p256               = { version = "0.13.2", default-features = false, features = ["arithmetic"] }
sha2               = { version = "0.10.8", default-features = false}
smart-leds         = "0.4.0"
ssd1306            = "0.8.4"
static_cell        = { version = "2.0.0", features = ["nightly"] }

[build-dependencies]
build-alert = "0.1.6"

[features]
default              = ["rt", "vectored", "zero-rtc-bss", "embassy-integrated-timers"]
async                = ["esp-hal-common/async"]
debug                = ["esp-hal-common/debug"]
defmt                = ["esp-hal-common/defmt", "esp-println/defmt-espflash"]
direct-vectoring     = ["esp-hal-common/direct-vectoring"]
eh1                  = ["esp-hal-common/eh1"]
embedded-io          = ["esp-hal-common/embedded-io"]
interrupt-preemption = ["esp-hal-common/interrupt-preemption"]
log                  = ["esp-hal-common/log", "esp-println/log"]
rt                   = ["esp-hal-common/rt-riscv"]
ufmt                 = ["esp-hal-common/ufmt"]
vectored             = ["esp-hal-common/vectored"]
flip-link            = ["esp-hal-common/flip-link"]

# Initialize / clear data sections and RTC memory
zero-rtc-bss  = ["esp-hal-common/rv-zero-rtc-bss"]
init-data     = ["esp-hal-common/rv-init-data"]
init-rtc-data = ["esp-hal-common/rv-init-rtc-data"]

# Embassy support
embassy                    = ["esp-hal-common/embassy"]
embassy-executor-interrupt = ["esp-hal-common/embassy-executor-interrupt"]
embassy-executor-thread    = ["esp-hal-common/embassy-executor-thread"]
embassy-integrated-timers  = ["esp-hal-common/embassy-integrated-timers"]
embassy-time-systick       = ["esp-hal-common/embassy-time-systick", "embassy-time/tick-hz-16_000_000"]
embassy-time-timg0         = ["esp-hal-common/embassy-time-timg0",   "embassy-time/tick-hz-1_000_000"]

[profile.release]
debug = true

[[example]]
name              = "spi_eh1_loopback"
required-features = ["eh1"]

[[example]]
name              = "spi_eh1_device_loopback"
required-features = ["eh1"]

[[example]]
name              = "embassy_hello_world"
required-features = ["embassy", "embassy-executor-thread"]

[[example]]
name              = "embassy_multiprio"
required-features = ["embassy", "embassy-executor-thread", "embassy-executor-interrupt"]

[[example]]
name              = "embassy_i2c"
required-features = ["async", "embassy", "embassy-executor-thread"]

[[example]]
name              = "embassy_serial"
required-features = ["async", "embassy", "embassy-executor-thread"]

[[example]]
name              = "embassy_spi"
required-features = ["async", "embassy", "embassy-executor-thread"]

[[example]]
name              = "embassy_wait"
required-features = ["async", "embassy", "embassy-executor-thread"]

[[example]]
name              = "embassy_rmt_tx"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "embassy_rmt_rx"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "interrupt_preemption"
required-features = ["interrupt-preemption"]

[[example]]
name              = "direct-vectoring"
required-features = ["direct-vectoring"]

[[example]]
name              = "embassy_i2s_sound"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "embassy_i2s_read"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "embassy_parl_io_tx"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "embassy_parl_io_rx"
required-features = ["embassy", "async", "embassy-executor-thread"]

[[example]]
name              = "embassy_usb_serial_jtag"
required-features = ["embassy", "async", "embassy-executor-thread"]
