[package]
name    = "esp32h2-hal"
version = "0.1.0"
authors = [
    "Kirill Mikhailov <playfulfence@gmail.com>",
    "Jesse Braham <jesse@beta7.io>",
    "Sergio Gasquez Arcos <sergio.gasquez@gmail.com",
]
edition      = "2021"
rust-version = "1.60.0"
description  = "HAL for ESP32-H2 microcontrollers"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

keywords = [
    "embedded",
    "embedded-hal",
    "esp",
    "esp32h2",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[dependencies]
cfg-if             = "1.0.0"
embassy-time       = { version = "0.1.1", features = ["nightly"], optional = true }
embedded-hal       = { version = "0.2.7", features = ["unproven"] }
embedded-hal-1     = { version = "=1.0.0-alpha.10", optional = true, package = "embedded-hal" }
embedded-hal-async = { version = "0.2.0-alpha.1", optional = true }
embedded-hal-nb    = { version = "=1.0.0-alpha.2", optional = true }
embedded-can       = { version = "0.4.1", optional = true }
esp-hal-common     = { version = "0.9.0",  features = ["esp32h2"], path = "../esp-hal-common" }

[dev-dependencies]
aes               = "0.8.2"
critical-section  = "1.1.1"
crypto-bigint     = { version = "0.5.2", default-features = false }
embassy-executor  = { version = "0.2.0", features = ["nightly", "integrated-timers", "arch-riscv32", "executor-thread"] }
embedded-graphics = "0.7.1"
esp-backtrace     = { version = "0.7.0", features = ["esp32h2", "panic-handler", "exception-handler", "print-uart"] }
esp-hal-smartled  = { version = "0.2.0", features = ["esp32h2"], path = "../esp-hal-smartled" }
esp-println       = { version = "0.5.0", features = ["esp32h2"] }
lis3dh-async      = "0.7.0"
sha2              = { version = "0.10.6", default-features = false}
smart-leds        = "0.3.0"
ssd1306           = "0.7.1"
static_cell       = "1.0.0"
heapless          = "0.7.16"

[features]
default              = ["rt", "vectored", "esp-hal-common/rv-zero-rtc-bss"]
debug                = ["esp-hal-common/debug"]
direct-boot          = ["esp-hal-common/rv-init-data", "esp-hal-common/rv-init-rtc-data"]
eh1                  = ["esp-hal-common/eh1", "dep:embedded-hal-1", "dep:embedded-hal-nb", "dep:embedded-can"]
rt                   = []
ufmt                 = ["esp-hal-common/ufmt"]
vectored             = ["esp-hal-common/vectored"]
async                = ["esp-hal-common/async", "embedded-hal-async"]
embassy              = ["esp-hal-common/embassy"]
embassy-time-systick = ["esp-hal-common/embassy-time-systick", "embassy-time/tick-hz-16_000_000"]
embassy-time-timg0   = ["esp-hal-common/embassy-time-timg0",   "embassy-time/tick-hz-1_000_000"]
interrupt-preemption = ["esp-hal-common/interrupt-preemption"]

[[example]]
name              = "spi_eh1_loopback"
required-features = ["eh1"]

[[example]]
name              = "spi_eh1_device_loopback"
required-features = ["eh1"]

[[example]]
name              = "embassy_hello_world"
required-features = ["embassy"]

[[example]]
name              = "embassy_i2c"
required-features = ["async", "embassy", "embassy-time-systick"]

[[example]]
name              = "embassy_serial"
required-features = ["async", "embassy"]

[[example]]
name              = "embassy_spi"
required-features = ["async", "embassy"]

[[example]]
name              = "embassy_wait"
required-features = ["async", "embassy"]

[[example]]
name              = "interrupt_preemption"
required-features = ["interrupt-preemption"]
