blank_issues_enabled: true
contact_links:
  - name: Ask questions in Matrix channel (Recommended)
    url: https://matrix.to/#/#esp-rs:matrix.org
    about: Ask any questions directly in our Matrix channel.
