[device]
name  = "esp32c6"
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "aes",
    "apb_saradc",
    "assist_debug",
    "atomic",
    "dma",
    "ds",
    "ecc",
    "efuse",
    "extmem",
    "gpio",
    "gpio_sd",
    "hinf",
    "hmac",
    "hp_apm",
    "hp_sys",
    "i2c0",
    "i2s0",
    "interrupt_core0",
    "intpri",
    "io_mux",
    "ledc",
    "lp_ana",
    "lp_aon",
    "lp_apm",
    "lp_apm0",
    "lp_clkrst",
    "lp_i2c0",
    "lp_i2c_ana_mst",
    "lp_io",
    "lp_peri",
    "lp_tee",
    "lp_timer",
    "lp_uart",
    "lp_wdt",
    "mcpwm0",
    "mem_monitor",
    "otp_debug",
    "parl_io",
    "pau",
    "pcnt",
    "pcr",
    "pmu",
    "rmt",
    "rng",
    "rsa",
    "sha",
    "slchost",
    "soc_etm",
    "spi0",
    "spi1",
    "spi2",
    "systimer",
    "tee",
    "timg0",
    "timg1",
    "trace0",
    "twai0",
    "twai1",
    "uart0",
    "uart1",
    "uhci0",
    "usb_device",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "adc",
    "assist_debug_sp_monitor",
    "assist_debug_region_monitor",
    "gdma",
    "large_intr_status",
    "plic",
    "phy",
    "bt",
    "wifi",
    "wifi6",
    "ieee802154",
    "lp_core",

    # ROM capabilities
    "rom_crc_le",
    "rom_crc_be",
    "rom_md5_bsd",

    # Wakeup SOC based on ESP-IDF:
    "pm_support_wifi_wakeup",
    "pm_support_beacon_wakeup",
    "pm_support_bt_wakeup",
    "gpio_support_deepsleep_wakeup",
    "uart_support_wakeup_int",
    "pm_support_ext1_wakeup",
]

memory = [{ name = "dram", start = 0x4080_0000, end = 0x4088_0000 }]
