[device]
name  = "esp32h2"
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "aes",
    "apb_saradc",
    "assist_debug",
    "dma",
    "ds",
    "ecc",
    "efuse",
    "gpio",
    "gpio_sd",
    "hmac",
    "hp_apm",
    "hp_sys",
    "i2c0",
    "i2c1",
    "i2s0",
    "interrupt_core0",
    "intpri",
    "io_mux",
    "ledc",
    "lp_ana",
    "lp_aon",
    "lp_apm",
    "lp_clkrst",
    "lp_peri",
    "lp_timer",
    "lp_wdt",
    "mcpwm0",
    "mem_monitor",
    "modem_lpcon",
    "modem_syscon",
    "otp_debug",
    "parl_io",
    "pau",
    "pcnt",
    "pcr",
    "pmu",
    "rmt",
    "rng",
    "rsa",
    "sha",
    "soc_etm",
    "spi0",
    "spi1",
    "spi2",
    "systimer",
    "tee",
    "timg0",
    "timg1",
    "trace0",
    "twai0",
    "uart0",
    "uart1",
    "uhci0",
    "usb_device",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "adc",
    "assist_debug_sp_monitor",
    "assist_debug_region_monitor",
    "gdma",
    "plic",
    "phy",
    "bt",
    "ieee802154",

    # ROM capabilities
    "rom_crc_le",
    "rom_crc_be",
    "rom_md5_bsd",
]
