[device]
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "apb_ctrl",
    "apb_saradc",
    "assist_debug",
    "dma",
    "ecc",
    "efuse",
    "extmem",
    "gpio",
    "i2c0",
    "interrupt_core0",
    "io_mux",
    "ledc",
    "rng",
    "rtc_cntl",
    "sensitive",
    "sha",
    "spi0",
    "spi1",
    "spi2",
    "system",
    "systimer",
    "timg0",
    "uart0",
    "uart1",
    "xts_aes",
    "assist_debug_sp_monitor",

    # Additional peripherals defined by us (the developers):
    "adc",
    "gdma",
    "radio",
    "phy",
    "bt",
    "wifi",

    # Wakeup SOC based on ESP-IDF:
    "pm_support_wifi_wakeup",
    "pm_support_bt_wakeup",
    "uart_support_wakeup_int",
    "gpio_support_deepsleep_wakeup",
]
