[package]
name          = "xtensa-lx"
version       = "0.12.0"
edition       = "2024"
rust-version  = "1.86.0"
description   = "Low-level access to Xtensa LX processors and peripherals"
documentation = "https://docs.espressif.com/projects/rust/xtensa-lx/latest/"
repository    = "https://github.com/esp-rs/esp-hal"
license       = "MIT OR Apache-2.0"
categories    = ["embedded", "hardware-support", "no-std"]
keywords      = ["lx", "peripheral", "register", "xtensa"]

[package.metadata.espressif]
requires_target = ["xtensa-esp32-none-elf", "xtensa-esp32s2-none-elf", "xtensa-esp32s3-none-elf"]

[lib]
bench = false
test  = false

[dependencies]
critical-section  = "1.2.0"

[features]
