[package]
name    = "esp32s3-hal"
version = "0.11.0"
authors = [
    "Jesse Braham <jesse@beta7.io>",
    "Bj√∂rn Quentin <bjoern.quentin@mobile-j.de>",
]
edition      = "2021"
rust-version = "1.65.0"
description  = "HAL for ESP32-S3 microcontrollers"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

keywords = [
    "embedded",
    "embedded-hal",
    "esp",
    "esp32s3",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]

[dependencies]
esp-hal-common = { version = "0.11.0", features = ["esp32s3"], path = "../esp-hal-common" }
embassy-time   = { version = "0.1.3", features = ["nightly"], optional = true }
r0             = { version = "1.0.0",  optional = true }

[dev-dependencies]
aes                = "0.8.3"
critical-section   = "1.1.2"
crypto-bigint      = { version = "0.5.2", default-features = false}
embassy-executor   = { version = "0.2.0", features = ["nightly", "integrated-timers", "arch-xtensa", "executor-thread"] }
embedded-graphics  = "0.8.1"
embedded-hal       = { version = "0.2.7",  features = ["unproven"] }
embedded-hal-1     = { version = "=1.0.0-rc.1", package = "embedded-hal" }
embedded-hal-async = "=1.0.0-rc.1"
embedded-can       = "0.4.1"
embedded-io-async  = "0.5.0"
esp-alloc          = "0.3.0"
esp-backtrace      = { version = "0.7.0", features = ["esp32s3", "panic-handler", "exception-handler", "print-uart"] }
esp-hal-smartled   = { version = "0.4.0", features = ["esp32s3"], path = "../esp-hal-smartled" }
esp-println        = { version = "0.5.0", features = ["esp32s3", "log"] }
heapless           = "0.7.16"
hmac               = { version = "0.12.1", default-features = false }
lis3dh-async       = { git = "https://github.com/jessebraham/lis3dh-rs-async", branch = "feature/eh-rc1" }
sha2               = { version = "0.10.7", default-features = false}
smart-leds         = "0.3.0"
ssd1306            = "0.8.0"
static_cell        = "1.2.0"
usb-device         = "0.2.9"
usbd-serial        = "0.1.1"

[features]
default              = ["rt", "vectored"]
debug                = ["esp-hal-common/debug"]
direct-boot          = ["r0"]
eh1                  = ["esp-hal-common/eh1"]
rt                   = []
ufmt                 = ["esp-hal-common/ufmt"]
vectored             = ["esp-hal-common/vectored"]
async                = ["esp-hal-common/async"]
embassy              = ["esp-hal-common/embassy"]
embassy-time-systick = ["esp-hal-common/embassy-time-systick", "embassy-time/tick-hz-16_000_000"]
embassy-time-timg0   = ["esp-hal-common/embassy-time-timg0", "embassy-time/tick-hz-1_000_000"]

psram     = []
psram_2m  = ["esp-hal-common/psram_2m", "psram"]
psram_4m  = ["esp-hal-common/psram_4m", "psram"]
psram_8m  = ["esp-hal-common/psram_8m", "psram"]
opsram_2m  = ["esp-hal-common/opsram_2m", "psram"]
opsram_4m  = ["esp-hal-common/opsram_4m", "psram"]
opsram_8m  = ["esp-hal-common/opsram_8m", "psram"]

[profile.release]
debug = true

[[example]]
name              = "spi_eh1_loopback"
required-features = ["eh1"]

[[example]]
name              = "spi_eh1_device_loopback"
required-features = ["eh1"]

[[example]]
name              = "embassy_hello_world"
required-features = ["embassy"]

[[example]]
name              = "embassy_wait"
required-features = ["embassy", "async"]

[[example]]
name              = "embassy_spi"
required-features = ["embassy", "async"]

[[example]]
name              = "psram"
required-features = ["psram_2m"]

[[example]]
name              = "octal_psram"
required-features = ["opsram_2m"]

[[example]]
name              = "embassy_serial"
required-features = ["embassy", "async"]

[[example]]
name              = "embassy_i2c"
required-features = ["embassy", "async"]
