[package]
name    = "esp-hal-procmacros"
version = "0.1.0"
authors = [
    "Jesse Braham <jesse@beta7.io>",
    "Bj√∂rn Quentin <bjoern.quentin@mobile-j.de>",
]
edition      = "2021"
rust-version = "1.60.0"
description  = "Procedural macros for ESP-HAL"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.14"
syn = {version = "1.0", features = ["extra-traits", "full"]}
proc-macro-error = "1.0.4"

[features]
rtc_slow = []
xtensa = []
riscv = []
interrupt = []