[package]
name         = "esp-hal-procmacros"
version      = "0.8.0"
edition      = "2021"
rust-version = "1.67.0"
description  = "Procedural macros for ESP-HAL"
repository   = "https://github.com/esp-rs/esp-hal"
license      = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
features = ["esp32c3", "embassy", "interrupt", "ram"]

[lib]
proc-macro = true

[dependencies]
darling          = "0.20.3"
litrs            = "0.4.1"
object           = { version = "0.32.1", optional = true }
proc-macro-crate = "2.0.1"
proc-macro-error = "1.0.4"
proc-macro2      = "1.0.70"
quote            = "1.0.33"
syn              = { version = "2.0.40", features = ["extra-traits", "full"] }

[features]
# Select a target device:
esp32       = []
esp32c2     = []
esp32c3     = []
esp32c6     = ["dep:object"]
esp32c6-lp  = []
esp32h2     = []
esp32s2     = ["dep:object"]
esp32s2-ulp = []
esp32s3     = ["dep:object"]
esp32s3-ulp = []

# Gated features:
embassy       = []
enum-dispatch = []
interrupt     = []
ram           = []
rtc_slow      = []
