[alias]
xtask    = "run --package xtask --"
xclean   = "xtask clean"
xdoc     = "run --package xtask --features=deploy-docs,preview-docs --"
xfmt     = "xtask fmt-packages"
qa       = "xtask run example qa-test"
xcheck   = "run --quiet --package xtask --features=semver-checks --"
xrelease = "run --package xtask --features=release -- release"
