[package]
name    = "touch"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
critical-section = "1.1.3"
esp-backtrace = { path = "../../../esp-backtrace", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { path = "../../../esp-bootloader-esp-idf" }
esp-hal = { path = "../../../esp-hal", features = ["log-04", "unstable"] }
esp-println = { path = "../../../esp-println", features = ["log-04"] }

[features]
esp32 = ["esp-backtrace/esp32", "esp-bootloader-esp-idf/esp32", "esp-hal/esp32"]

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1
