[package]
name    = "embassy-access-point"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
edge-dhcp = "0.5.0"
edge-nal = "0.5.0"
edge-nal-embassy = "0.6.0"
embassy-executor = "0.9.0"
embassy-net = { version = "0.7.0", features = [
    "dhcpv4",
    "medium-ethernet",
    "tcp",
    "udp",
] }
embassy-time = "0.5.0"
embedded-io-async = "0.6.1"
esp-alloc = { path = "../../../esp-alloc" }
esp-backtrace = { path = "../../../esp-backtrace", features = [
    "panic-handler",
    "println",
] }
esp-bootloader-esp-idf = { path = "../../../esp-bootloader-esp-idf" }
esp-hal = { path = "../../../esp-hal", features = ["log-04", "unstable"] }
esp-println = { path = "../../../esp-println", features = ["log-04"] }
esp-rtos = { path = "../../../esp-rtos", features = ["embassy", "log-04"] }
esp-radio = { path = "../../../esp-radio", features = [
    "log-04",
    "unstable",
    "wifi",
] }
log = "0.4.27"
static_cell = "2.1.0"

[features]
esp32 = [
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-hal/esp32",
    "esp-rtos/esp32",
    "esp-radio/esp32",
]
esp32c2 = [
    "esp-backtrace/esp32c2",
    "esp-bootloader-esp-idf/esp32c2",
    "esp-hal/esp32c2",
    "esp-rtos/esp32c2",
    "esp-radio/esp32c2",
]
esp32c3 = [
    "esp-backtrace/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
    "esp-hal/esp32c3",
    "esp-rtos/esp32c3",
    "esp-radio/esp32c3",
]
esp32c6 = [
    "esp-backtrace/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-hal/esp32c6",
    "esp-rtos/esp32c6",
    "esp-radio/esp32c6",
]
esp32s2 = [
    "esp-backtrace/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
    "esp-hal/esp32s2",
    "esp-rtos/esp32s2",
    "esp-radio/esp32s2",
]
esp32s3 = [
    "esp-backtrace/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-hal/esp32s3",
    "esp-rtos/esp32s3",
    "esp-radio/esp32s3",
]

[profile.release]
debug            = true
debug-assertions = true
lto              = "fat"
codegen-units    = 1
