[target.riscv32imc-unknown-none-elf]
runner = "espflash --format direct-boot --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x"
]

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = [ "core" ]
