[target.xtensa-esp32s2-none-elf]
runner = "xtensa-esp32s2-elf-gdb -q -x xtensa.gdb"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlink.x",
]
target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["core"]
